from tkinter import*
root=Tk()
img=PhotoImage(file='starbus.png')
Label(root,image=img).pack()
Label(root,text='Online Bus Booking System',bg='light blue',fg='red',font='Arial 50').pack()
Label(root,text='Name: RUDRA YADAV').pack()
Label(root,text='Name: 221B312').pack()
Label(root,text='Name: 6393276396').pack()
Label(root,text='Submittd to: Dr. Mahesh Kumar',bg='light blue',fg='red',font='Arial 50').pack()
Label(root,text='Project Based Learning').pack()
root.mainloop()
